name: Build Minified Userscript

on:
  push:
    paths-ignore:
      - 'min/**'

permissions:
  contents: write

jobs:
  minify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Prepare output dir
        run: mkdir -p min

      # Extract header (prefer /* @preserve ... @endpreserve */, else // ==UserScript== ... ==/UserScript==)
      - name: Extract userscript header
        shell: bash
        run: |
          set -euo pipefail
          if grep -qE '^\s*/\*\s*@preserve' overlay.user.js; then
            # capture the whole preserve block
            sed -n '/^\s*\/\*\s*@preserve/,/@endpreserve \*\//p' overlay.user.js > /tmp/header.user.js
          else
            # capture just the ==UserScript== block
            awk '/^\/\/[[:space:]]*==UserScript==/{f=1} f{print} /^\/\/[[:space:]]*==\/UserScript==/{exit}' overlay.user.js > /tmp/header.user.js
          fi
          # sanity check
          test -s /tmp/header.user.js || (echo "Header not found" && exit 1)

      # Minify the code (robust for modern JS)
      - name: Minify with esbuild
        run: |
          npx esbuild overlay.user.js --minify --legal-comments=none --outfile=/tmp/code.min.js

      # Combine header + minified code into final userscript name
      - name: Assemble final userscript
        run: |
          printf '%s\n\n' "$(cat /tmp/header.user.js)" > min/overlay.min.user.js
          cat /tmp/code.min.js >> min/overlay.min.user.js

      # Replace the URL to point to minified version
      - name: Update self-reference URL
        run: |
          sed -i 's|https://github.com/HailXD/Hails-Overlay-Pro/raw/refs/heads/main/overlay\.user\.js|https://github.com/HailXD/Hails-Overlay-Pro/raw/refs/heads/main/min/overlay.min.user.js|g' min/overlay.min.user.js

      - name: Show what we'll commit (debug)
        run: |
          echo "=== min/ tree ==="
          find min -type f -maxdepth 2 -print

      - name: Commit minified userscript
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          file_pattern: 'min/overlay.min.user.js'
          commit_message: 'bot: Add minified userscript'
