name: Auto Minify
on:
  push:
    paths-ignore:
      - 'min/**'
permissions:
  contents: write

jobs:
  minify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Reset min/ directory
        run: rm -rf min && mkdir -p min

      - name: Auto minify to min/
        uses: nizarmah/auto-minify@v3
        with:
          directory: .
          output: min
          overwrite: false
          maxdepth: 1          # include files in repo root
          js_engine: uglify-js # avoid babel-minify crash

      # The action creates: min/overlay.user.js -> rename to overlay.min.user.js
      - name: Rename *.user.js -> *.min.user.js
        shell: bash
        run: |
          shopt -s nullglob
          for f in min/*.user.js; do
            mv "$f" "${f%.user.js}.min.user.js"
          done

      - name: Show what we’ll commit (debug)
        run: |
          echo "=== min/ tree ==="
          find min -type f -maxdepth 2 -print

      - name: Commit minified files
        id: commit
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          file_pattern: 'min/**'
          commit_message: 'bot: Add auto minified files'

      - name: Commit result
        run: echo "changes_detected=${{ steps.commit.outputs.changes_detected }}"
